#!/usr/bin/env bash
# =============================================================================
# MODULE  : 03_aide.sh
# TITLE   : AIDE — File Integrity Monitoring
# OS      : Red Hat Enterprise Linux 9 / Rocky Linux 9
# CIS REF : CIS RHEL 9 Benchmark — Section 1.3 (Filesystem Integrity Checking)
#
# CHECKS  :
#   1.  AIDE package installed
#   2.  AIDE configuration file exists (/etc/aide.conf)
#   3.  AIDE database initialised (/var/lib/aide/aide.db.gz)
#   4.  AIDE cron job configured (0 5 * * * /usr/sbin/aide --check)
#   5.  AIDE cron job file permissions secured
#   6.  Verify AIDE binary integrity (checksum)
#
# BEHAVIOUR:
#   - Installs AIDE via dnf if missing
#   - Initialises the database if not present (can take a few minutes)
#   - Creates /etc/cron.d/aide with the required schedule
#   - Remediates any misconfigured cron entry automatically
#
# EXIT CODES:
#   0 — All checks passed (or remediated successfully)
#   1 — One or more checks failed
#   2 — Skipped (unsupported OS / dnf unavailable)
#
# USAGE   : sudo bash 03_aide.sh
# =============================================================================

set -euo pipefail

# ── Colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

pass()  { echo -e "${GREEN}[PASS]${RESET}  $*"; }
fail()  { echo -e "${RED}[FAIL]${RESET}  $*"; }
info()  { echo -e "${CYAN}[INFO]${RESET}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
hdr()   { echo -e "\n${BOLD}── $* ──${RESET}"; }

OVERALL=0
mark_fail() { OVERALL=1; }

# ── Constants ─────────────────────────────────────────────────────────────────
AIDE_BIN="/usr/sbin/aide"
AIDE_CONF="/etc/aide.conf"
AIDE_DB="/var/lib/aide/aide.db.gz"
AIDE_DB_NEW="/var/lib/aide/aide.db.new.gz"
AIDE_LOG_DIR="/var/log/aide"
CRON_FILE="/etc/cron.d/aide"
CRON_USER="root"
CRON_SCHEDULE="0 5 * * *"
CRON_CMD="/usr/sbin/aide --check"
CRON_FULL="${CRON_SCHEDULE} ${CRON_USER} ${CRON_CMD}"

# ── OS Detection ──────────────────────────────────────────────────────────────
hdr "OS Detection"

if [[ ! -f /etc/os-release ]]; then
    warn "Cannot detect OS — /etc/os-release not found. Skipping module."
    exit 2
fi

source /etc/os-release
MAJOR_VER="${VERSION_ID%%.*}"

if [[ "${ID}" != "rhel" && "${ID}" != "rocky" ]] || [[ "${MAJOR_VER}" != "9" ]]; then
    warn "Unsupported OS: ${ID} ${VERSION_ID}. This module targets RHEL/Rocky Linux 9."
    exit 2
fi

info "Detected OS : ${PRETTY_NAME}"

# Ensure dnf is available
if ! command -v dnf &>/dev/null; then
    fail "dnf package manager not found — cannot install AIDE."
    exit 2
fi

# =============================================================================
# CHECK 1 — AIDE Package Installed
# =============================================================================
hdr "Check 1 — AIDE Package Installed"
info "Audit  : rpm -q aide"

if rpm -q aide &>/dev/null; then
    AIDE_VER=$(rpm -q --queryformat "%{VERSION}" aide)
    pass "AIDE is installed (version ${AIDE_VER})."
else
    fail "AIDE package is NOT installed."
    info "Remediation: Installing AIDE via dnf ..."

    if dnf install -y aide &>/dev/null; then
        AIDE_VER=$(rpm -q --queryformat "%{VERSION}" aide)
        pass "AIDE installed successfully (version ${AIDE_VER})."
    else
        fail "dnf install aide FAILED — check network/repo access."
        mark_fail
        # Cannot continue without the binary
        echo ""
        echo "──────────────────────────────────────────────────────"
        fail "Module 03_aide — CRITICAL FAILURE (AIDE not installable)"
        exit 1
    fi
fi

# =============================================================================
# CHECK 2 — AIDE Configuration File
# =============================================================================
hdr "Check 2 — AIDE Configuration File"
info "Audit  : test -f ${AIDE_CONF}"

if [[ -f "${AIDE_CONF}" ]]; then
    pass "AIDE configuration file found : ${AIDE_CONF}"

    # Show monitored paths summary
    MONITORED_COUNT=$(grep -cE '^/' "${AIDE_CONF}" 2>/dev/null || echo "0")
    info "Monitored path rules in config : ${MONITORED_COUNT}"
else
    fail "AIDE configuration file NOT found : ${AIDE_CONF}"
    info "Remediation: Creating minimal AIDE configuration ..."

    mkdir -p "$(dirname "${AIDE_CONF}")"

    cat > "${AIDE_CONF}" << 'EOF'
# /etc/aide.conf — generated by 03_aide.sh hardening module
# Reference: CIS RHEL 9 Benchmark Section 1.3

# ── Database locations ────────────────────────────────────────────
database_in=file:/var/lib/aide/aide.db.gz
database_out=file:/var/lib/aide/aide.db.new.gz
database_new=file:/var/lib/aide/aide.db.new.gz
gzip_dbout=yes

# ── Report settings ───────────────────────────────────────────────
report_url=file:/var/log/aide/aide.log
report_url=stdout
verbose=5

# ── Attribute groups ──────────────────────────────────────────────
FIPSR = p+i+n+u+g+s+m+c+acl+selinux+xattrs+sha256
NORMAL = sha256+p+i+n+u+g+s+m+c+acl+selinux+xattrs
PERMS  = p+i+u+g+acl+selinux
CONTENT= sha256+ftype

# ── Monitored paths ───────────────────────────────────────────────
# Critical system binaries
/boot            FIPSR
/bin             FIPSR
/sbin            FIPSR
/lib             FIPSR
/lib64           FIPSR
/usr/bin         FIPSR
/usr/sbin        FIPSR
/usr/lib         FIPSR
/usr/lib64       FIPSR
/usr/libexec     FIPSR

# Configuration files
/etc             NORMAL

# AIDE itself
/usr/sbin/aide   FIPSR

# ── Excluded paths ────────────────────────────────────────────────
!/etc/mtab
!/etc/.*~
!/etc/adjtime
!/etc/lvm/cache
!/var/log/aide
!/proc
!/sys
!/dev
!/run
!/tmp
!/var/tmp
!/var/spool
!/var/cache
!/var/lib/aide
!/home
EOF

    if [[ -f "${AIDE_CONF}" ]]; then
        pass "Minimal AIDE configuration created at ${AIDE_CONF}"
    else
        fail "Failed to create AIDE configuration."
        mark_fail
    fi
fi

# Secure the config file
chmod 600 "${AIDE_CONF}"
chown root:root "${AIDE_CONF}"
info "Permissions set on ${AIDE_CONF} → 600 root:root"

# =============================================================================
# CHECK 3 — AIDE Database Initialised
# =============================================================================
hdr "Check 3 — AIDE Database Initialised"
info "Audit  : test -f ${AIDE_DB}"

# Ensure log directory exists
mkdir -p "${AIDE_LOG_DIR}"
chmod 700 "${AIDE_LOG_DIR}"
chown root:root "${AIDE_LOG_DIR}"

if [[ -f "${AIDE_DB}" ]]; then
    DB_DATE=$(stat -c "%y" "${AIDE_DB}" | cut -d'.' -f1)
    DB_SIZE=$(du -sh "${AIDE_DB}" | cut -f1)
    pass "AIDE database found : ${AIDE_DB}"
    info "Database created    : ${DB_DATE}"
    info "Database size       : ${DB_SIZE}"
else
    fail "AIDE database NOT found : ${AIDE_DB}"
    info "Remediation: Initialising AIDE database (this may take several minutes) ..."
    warn "Please do NOT interrupt — incomplete initialisation produces a corrupt database."
    echo ""

    # Run aide --init and show progress
    if aide --init --config="${AIDE_CONF}" 2>&1 | tee -a "${AIDE_LOG_DIR}/aide_init.log"; then
        echo ""
        # aide --init writes to aide.db.new.gz — rename to aide.db.gz
        if [[ -f "${AIDE_DB_NEW}" ]]; then
            mv "${AIDE_DB_NEW}" "${AIDE_DB}"
            chmod 600 "${AIDE_DB}"
            chown root:root "${AIDE_DB}"
            DB_SIZE=$(du -sh "${AIDE_DB}" | cut -f1)
            pass "AIDE database initialised : ${AIDE_DB} (${DB_SIZE})"
        else
            fail "aide --init ran but ${AIDE_DB_NEW} was not created."
            info "Check ${AIDE_LOG_DIR}/aide_init.log for errors."
            mark_fail
        fi
    else
        fail "aide --init returned non-zero exit code."
        info "Check ${AIDE_LOG_DIR}/aide_init.log for details."
        mark_fail
    fi
fi

# =============================================================================
# CHECK 4 — AIDE Cron Job Configured
# =============================================================================
hdr "Check 4 — AIDE Cron Job (0 5 * * *)"
info "Audit  : cat ${CRON_FILE}"
info "Expect : ${CRON_FULL}"

CRON_OK=0

if [[ -f "${CRON_FILE}" ]]; then
    info "Cron file exists : ${CRON_FILE}"
    info "Current content  :"
    grep -v '^#' "${CRON_FILE}" | grep -v '^$' | sed 's/^/        /' || true
    echo ""

    # Verify the exact schedule, user, and command are present
    if grep -qE "^0 5 \* \* \* +root +/usr/sbin/aide --check" "${CRON_FILE}"; then
        pass "Cron entry is correctly configured."
        CRON_OK=1
    else
        fail "Cron entry exists but does not match the required schedule/command."
        warn "Expected : ${CRON_FULL}"
    fi
else
    info "Cron file not found : ${CRON_FILE} — will create it."
fi

if [[ "${CRON_OK}" -eq 0 ]]; then
    info "Remediation: Writing cron job to ${CRON_FILE} ..."

    cat > "${CRON_FILE}" << EOF
# /etc/cron.d/aide — AIDE file integrity check
# Generated by 03_aide.sh hardening module
# CIS RHEL 9 Benchmark — Section 1.3
#
# Runs every day at 05:00 and logs output to ${AIDE_LOG_DIR}/aide_check.log
# Schedule : ${CRON_SCHEDULE}  (min hour dom mon dow)

SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

${CRON_SCHEDULE} ${CRON_USER} ${CRON_CMD} >> ${AIDE_LOG_DIR}/aide_check.log 2>&1
EOF

    # Verify the write
    if grep -qE "^0 5 \* \* \* +root +/usr/sbin/aide --check" "${CRON_FILE}"; then
        pass "Cron job created successfully in ${CRON_FILE}"
    else
        fail "Cron file was written but expected entry not found — manual review required."
        mark_fail
    fi
fi

# =============================================================================
# CHECK 5 — Cron File Permissions
# =============================================================================
hdr "Check 5 — Cron File Permissions"
info "Audit  : stat -c '%a %U %G' ${CRON_FILE}"

CRON_PERMS=$(stat -c "%a" "${CRON_FILE}" 2>/dev/null || echo "000")
CRON_OWNER=$(stat -c "%U:%G" "${CRON_FILE}" 2>/dev/null || echo "unknown")

if [[ "${CRON_PERMS}" == "600" || "${CRON_PERMS}" == "644" ]] && [[ "${CRON_OWNER}" == "root:root" ]]; then
    pass "Cron file permissions : ${CRON_PERMS} ${CRON_OWNER}"
else
    fail "Insecure cron file permissions : ${CRON_PERMS} ${CRON_OWNER}"
    info "Remediation: Securing ${CRON_FILE} ..."
    chmod 600 "${CRON_FILE}"
    chown root:root "${CRON_FILE}"

    FIXED_PERMS=$(stat -c "%a" "${CRON_FILE}")
    FIXED_OWNER=$(stat -c "%U:%G" "${CRON_FILE}")
    pass "Cron file permissions set to ${FIXED_PERMS} ${FIXED_OWNER}"
fi

# Also lock down the log directory
chmod 700 "${AIDE_LOG_DIR}"
chown root:root "${AIDE_LOG_DIR}"
info "Log directory permissions secured : ${AIDE_LOG_DIR} → 700 root:root"

# =============================================================================
# CHECK 6 — Verify AIDE Binary Integrity
# =============================================================================
hdr "Check 6 — AIDE Binary Integrity"
info "Audit  : rpm -V aide"

if rpm -V aide &>/dev/null; then
    pass "rpm -V aide — binary and files verified against RPM database (no changes)."
else
    CHANGED=$(rpm -V aide 2>/dev/null || true)
    fail "rpm -V aide detected discrepancies:"
    echo "${CHANGED}" | sed 's/^/        /'
    warn "If AIDE binary has been modified since install, reinstall the package:"
    info "  dnf reinstall aide"
    mark_fail
fi

# =============================================================================
# Summary of configured cron job
# =============================================================================
hdr "Cron Job Summary"

echo ""
echo -e "  ${BOLD}Schedule  :${RESET} ${CYAN}${CRON_SCHEDULE}${RESET}  (daily at 05:00)"
echo -e "  ${BOLD}Run as    :${RESET} ${CRON_USER}"
echo -e "  ${BOLD}Command   :${RESET} ${CRON_CMD}"
echo -e "  ${BOLD}Cron file :${RESET} ${CRON_FILE}"
echo -e "  ${BOLD}Log output:${RESET} ${AIDE_LOG_DIR}/aide_check.log"
echo -e "  ${BOLD}DB path   :${RESET} ${AIDE_DB}"
echo ""
info "To run a manual integrity check now:"
echo "        sudo aide --check --config=${AIDE_CONF}"
echo ""
info "To update the database after planned system changes:"
echo "        sudo aide --update --config=${AIDE_CONF}"
echo "        sudo mv ${AIDE_DB_NEW} ${AIDE_DB}"

# =============================================================================
# Result
# =============================================================================
echo ""
echo "──────────────────────────────────────────────────────"
if [[ "${OVERALL}" -eq 0 ]]; then
    pass "Module 03_aide — ALL CHECKS PASSED"
    exit 0
else
    fail "Module 03_aide — ONE OR MORE CHECKS FAILED"
    exit 1
fi
